name: test&accept_pr
on: pull_request
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
  accept_pr:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Accept PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = JSON.stringify(github.context.payload, undefined, 2)
            console.log(`The event payload: ${payload}`);
            const pr_number = github.context.payload.number;
            const myToken = core.getInput('myToken');
            const octokit = github.getOctokit(myToken);
            const { data: pullRequest } = await octokit.pulls.get({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: pr_number
            });
            console.log(pullRequest);
            const { data: pullRequestReview } = await octokit.pulls.createReview({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: pr_number,
              event: 'APPROVE',
              body: 'Automated approval'
            });
            console.log(pullRequestReview);